# Generated by Django 2.1.1 on 2018-11-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPRlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sluz',
            field=models.CharField(blank=True, choices=[(0, 'taki sobie'), (1, 'może być')], max_length=500, verbose_name='śluz'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='temperatura ciała'),
        ),
    ]
