# Generated by Django 2.1.1 on 2019-03-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPRlog', '0002_auto_20181102_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='period_day',
            field=models.IntegerField(null=True, verbose_name='Dzień cyklu'),
        ),
    ]
