# Generated by Django 2.2 on 2019-04-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NPRlog', '0003_measurement_period_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertileMucus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='śluz płodny')),
            ],
        ),
        migrations.CreateModel(
            name='NotFertileMucus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='śluz płodny')),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='sluz',
        ),
        migrations.AddField(
            model_name='measurement',
            name='fertile_mucus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NPRlog.FertileMucus'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='not_fertile_mucus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NPRlog.NotFertileMucus'),
        ),
    ]
