# Generated by Django 2.2 on 2019-04-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPRlog', '0005_auto_20190423_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='fertile_mucus',
            field=models.ManyToManyField(to='NPRlog.FertileMucus'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='not_fertile_mucus',
            field=models.ManyToManyField(to='NPRlog.NotFertileMucus'),
        ),
    ]
